FROM openjdk:8-jdk-alpine
# FROM amazoncorretto:8-alpine-jdk
MAINTAINER deepank.puri
COPY target/RestaurantBackend-0.0.1-SNAPSHOT.jar restaurant-backend-0.0.1.jar
ENTRYPOINT ["java","-jar","/restaurant-backend-0.0.1.jar"]